---
abstract: 'Perl interface to goo.gl'
author:
  - 'Magnus Erixzon <magnus@erixzon.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-Googl
requires:
  JSON::Any: 0
  LWP::UserAgent: 0
  WWW::Shorten: 1.98
resources:
  repository: http://github.com/merixzon/www-shorten-googl
version: 1.01
